// import { Inter } from "next/font/google";
// import { descriptors } from "chart.js/dist/core/core.defaults";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export const metadata = {
//   title: "Create Next App",
//   descriptions: "Generated by create next app"
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >{children}</body>
    </html>
  );
}
